### PR TITLE
Merge pull request #1 from RicardoVel73/RicardoVel73-patch-1

### PR DESCRIPTION
**Pull request by RicardoVel73**
Create HTML_2

### CODE REVIEW

**Review by emmanuellekamwa — COMMENTED** [review]
**STATUS: CHANGES REQUESTED 🛑🛠**
Hello @RicardoVel73 👋🏽
Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
- I can't review your pull request because you have merged it before approval. A pull request has to be approved first before you can merge. I think that it will be better if you create a new branch and start the project from there.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by RicardoVel73** [comment]
Please, I´m not getting anything of what you said, can you help me? What
should I do before I submit it again?

**Comment by emmanuellekamwa** [comment]
Hi. Just create another branch and start back the project from there

Le mar. 14 sept. 2021 à 22:29, RicardoVel73 ***@***.***> a
écrit :

> Please, I´m not getting anything of what you said, can you help me? What
> should I do before I submit it again?
>
> El mar, 14 sept 2021 a las 16:18, Kamwa Emmanuelle Alix (<

**Review by GzimAsani — COMMENTED** [review]
# Hello @RicardoVel73 

#### Hello Ricardo please refer to what the last review said. You should open a new pull request and then ask for another code review because  you have already merged this pull request :disappointed: . 

# Invalid Request :red_circle: 
- [ ] You should not merge a pull request before getting approved

## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
 You can also consider:

- [ ] Commit messages should be meaningful and descriptive about the changes made and not repetitions please keep this in mind for the next projects 

 Cheers and Happy coding!

 Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Review by GzimAsani — COMMENTED** [review]
# Hello @RicardoVel73 

#### Hello Ricardo please refer to what the last review said. You should open a new pull request and then ask for another code review because you have already merged this pull request :disappointed: . 

# Requested Changes :red_circle: 
- [ ] You should not merge a pull request before getting approved

## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
 You can also consider:

- [ ] Commit messages should be meaningful and descriptive about the changes made and not repetitions please keep this in mind for the next projects 

 Cheers and Happy coding!

 Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by RicardoVel73** [comment]
Your comments aren´t helping me at all. Please, be more specific. You told
me to create a new branch a submit it again and I did that (and wasted my
final attempt doing it). I can´t work like that. The first review did tell
me what to do.

**Comment by RicardoVel73** [comment]
THANK YOU!

**Pull request merged**
